---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  labels:
    app: redis
  namespace: redis
spec:
  serviceName: redis
  selector:
    matchLabels:
      app: redis
      role: master
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
        role: master
        tier: backend
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data-redis
        - name: config
          configMap:
            name: redis
            defaultMode: 420
        - name: redis-secret
          secret:
            secretName: redis-secret
            items:
              - key: redis_secret
                path: password
      containers:
        - name: redis
          image: redis
          args: ["/usr/local/etc/redis/redis.conf"]
          ports:
            - containerPort: 6379
          env:
            - name: REDIS_PASSWORD
              value: /usr/local/etc/redis/secrets/password
            - name: REDIS_PASSWORD
              value: {{ redis.log }}
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          volumeMounts:
            - name: data
              mountPath: /data
            - name: config
              mountPath: /usr/local/etc/redis/redis.conf
              subPath: redis.conf
            - name: redis-secret
              mountPath: /usr/local/etc/redis/secrets
              readOnly: true
