image:
  repository: golift/unifi-poller
  tag: 2.0.1
  pullPolicy: IfNotPresent

serviceAccount:
  create: true

config:
  poller:
    debug: false
    quiet: false
    plugins: []

  prometheus:
    disable: false
    http_listen: "0.0.0.0:9130"
    report_errors: false

  influxdb:
    disable: true

  unifi:
    dynamic: false
    defaults:
      role: "{{ organization_name }} Controller"
      user: "{{ unifi_user }}"
      pass: "{{ unifi_password }}"
      url: "https://{{ unifi_url }}:{{ unifi_port }}"
      sites:
        - all
      verify_ssl: true
      save_ids: true
      save_dpi: true
      save_sites: true
    controllers: []
