---
- name: Copy over nfs provisioner config file
  template:
    src: nfs-provisioner-helm.yaml
    dest: "{{ remote_tmp }}/config.yml"

- name: Deploy nfs provisioner
  community.kubernetes.helm:
    name: nfs-provisioner
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    chart_ref: stable/nfs-client-provisioner
    chart_version: 1.2.9
    release_namespace: kube-system
    update_repo_cache: yes
    values: "{{ remote_tmp }}/config.yml"
    
   
