---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: nfs-client-provisioner
  namespace: kube-system
spec:
  chart: stable/nfs-client-provisioner
  set:
    image.repository: {{ nfs_provisioner_image }}
    nfs.server: "192.186.40.10"
    nfs.path: "/media/datastore/data"
