image:
  repository: nodered/node-red
  tag: 1.2.5-12-arm64v8
  pullPolicy: IfNotPresent

service:
  port:
    port: 1880

persistence:
  data:
    enabled: true
    emptyDir: false
    storageClass: "nfs-client"
    accessMode: ReadWriteOnce
    mountPath: /data
