---
- name: Remove existing helm repo
  ignore_errors: yes
  shell:  "helm repo remove stable"
  args:
    warn: no

- name: Install helm repo
  shell:  "helm repo add stable {{ helm_chart_url }}"
  args:
    warn: no

- name: Update helm repo
  shell:  "helm repo update"
  args:
    warn: no
