---

- name: Add stable repository
  community.kubernetes.helm_repository:
    name: stable
    repo_url: "{{ helm_chart_url }}"


- name: Update helm repo
  shell:  "helm repo update"
  args:
    warn: no
