---
- hosts: master
  become: no
  roles:
    #- role: apps/redis
    #- role: apps/mariadb
    #- role: apps/ldap
    - role: apps/phpldapadmin
    #- role: apps/authelia
    #- role: apps/kube_dashboard
