---
- hosts: master
  become: no
  roles:
#    - role: apps/redis
    - role: apps/mariadb
#    - role: apps/phpmyadmin
#    - role: system/nfs/provisioner
#    - role: system/cert-manager
#    - role: system/get-cert
#    - role: system/traefik
#    - role: system/digitalocean-dyndns
