---

- hosts: k3s_cluster
  gather_facts: yes
  become: yes
  roles:
    - role: deploy/prereq
    - role: deploy/download
    - role: deploy/raspberrypi

#- hosts: master
#  become: yes
#  roles:
#    - role: deploy/k3s/master

- hosts: node
  become: yes
  roles:
    - role: deploy/k3s/node
