---
- hosts: master
  become: no
  vars_files:
    - ./secrets/secrets.var
  roles:
  #  - role: services/monitor/monitorstack
  #  - role: services/monitor/blackbox-exporter
  #  - role: services/monitor/speedtestprometheus
  #  - role: services/monitor/unifipoller
    - role: services/monitor/guacamole
