---
- hosts: master
  become: no
  vars_files:
    - ./secrets/secrets.var
  roles:
  #  - role: monitor/monitorstack
    - role: monitor/speedtestprometheus
    - role: monitor/unifipoller
    - role: monitor/uptimerobot
