---
- hosts: master
  become: no
  vars_files:
    - ./secrets/secrets.var
  roles:
    - role: monitor/monitorstack
    #- role: apps/mariadb
    #- role: apps/ldap
    #- role: apps/phpldapadmin
    #- role: apps/authelia
    #- role: apps/kube_dashboard
