---
- hosts: master
  become: no
  vars_files:
    - ./secrets/secrets.var
  roles:
    #- role: services/redis
    #- role: services/mariadb
    #- role: services/ldap
    - role: services/phpldapadmin
    #- role: services/authelia
    #- role: services/kube_dashboard
