---
#- hosts: k3s_cluster
#  become: yes
#  roles:
#    - role: deploy/system/essential

#- hosts: master
#  become: yes
#  roles:
#    - role: system/nfs/server

- hosts: master
  become: no
  vars_files:
    - ./secrets/secrets.var
  roles:
    - role: deploy/system/upgrade
    #- role: deploy/system/openshift
    #- role: andrewrothstein.kubernetes-helm
    #- role: deploy/system/helm_repo
    #- role: deploy/system/metallb
    #- role: deploy/system/nfs/provisioner
    #- role: deploy/ingress/cert_manager
    #- role: deploy/ingress/get_cert
    #- role: deploy/ingress/traefik
    #- role: deploy/ingress/digitalocean_dyndns
    #- role: deploy/ingress/traefik-ext
    #- role: deploy/system/kube_dashboard
