defaultRules:
  create: true
  rules:
    alertmanager: true
    etcd: false
    general: true
    k8s: true
    kubeApiserver: true
    kubeApiserverAvailability: true
    kubeApiserverError: true
    kubeApiserverSlos: true
    kubelet: true
    kubePrometheusGeneral: true
    kubePrometheusNodeAlerting: true
    kubePrometheusNodeRecording: true
    kubernetesAbsent: true
    kubernetesApps: true
    kubernetesResources: true
    kubernetesStorage: true
    kubernetesSystem: true
    kubeScheduler: true
    kubeStateMetrics: true
    network: true
    node: true
    prometheus: true
    prometheusOperator: true
    time: true
alertmanager:
  enabled: true
  alertmanagerSpec:
    image:
      repository: prom/alertmanager
      tag: v0.21.0
      sha: ""
grafana:
  enabled: true
  persistence:
    type: pvc
    enabled: true
    storageClassName: nfs-client
    accessModes:
      - ReadWriteOnce
    size: 2Gi
    finalizers:
      - kubernetes.io/pvc-protection
  extraVolumeMounts:
    - name: plugins
      mountPath: /var/lib/grafana/plugins
      subPath: configs/grafana/plugins
      readOnly: false
  plugins:
    - grafana-piechart-panel
    - grafana-clock-panel
  grafana.ini:
    analytics:
      check_for_updates: true
    grafana_net:
      url: https://grafana.net
    log:
      mode: console
      filters: ldap:debug
    paths:
      data: /var/lib/grafana/data
      logs: /var/log/grafana
      plugins: /var/lib/grafana/plugins
      provisioning: /etc/grafana/provisioning
    security:
      allow_embedding: structure
    server:
      enable_gzip: true
      root_url:
    auth.ldap:
      enabled: true
      config_file: /etc/grafana/ldap.toml
      allow_sign_up: true
    auth.proxy:
      enabled: true
      header_name: Remote-User
      header_property: username
      auto_sign_up: true
      sync_ttl: 60
      headers: Name:Remote-Name Email:Remote-Email Groups:Remote-Groups
      enable_login_token: true
  ldap:
    enabled: true
    config: |-
      [[servers]]
      host = "192.168.1.221"
      port = 389
      use_ssl = false
      start_tls = false
      ssl_skip_verify = false
      bind_dn = "cn=admin,dc=mccannclan,dc=family"
      bind_password = 'Jennifer.0211'
      search_filter = "(uid=%s)"
      search_base_dns = ["ou=users,dc=mccannclan,dc=family"]
      [servers.attributes]
      name = "givenName"
      surname = "sn"
      username = "uid"
      member_of = "memberOf"
      email =  "email"
      [[servers.group_mappings]]
      group_dn = "cn=admin,ou=groups,dc=mccannclan,dc=family"
      org_role = "Admin"
      grafana_admin = true
      [[servers.group_mappings]]
      group_dn = "cn=family,ou=groups,dc=mccannclan,dc=family"
      org_role = "Viewer"
  sidecar:
    enableUniqueFilenames: false
    dashboards:
      enabled: true
    datasources:
      enabled: true
    notifiers:
      enabled: true
kubeApiServer:
  enabled: true
kubelet:
  enabled: true
  namespace: kube-system
kubeControllerManager:
  enabled: true
coreDns:
  enabled: true
kubeDns:
  enabled: false
kubeProxy:
  enabled: false
kubeStateMetrics:
  enabled: true
kube-state-metrics:
  image:
    repository: carlosedp/kube-state-metrics
    tag: v1.9.6-arm64
    pullPolicy: IfNotPresent
nodeExporter:
  enabled: true
prometheusOperator:
  enabled: true
  kubeletService:
    enabled: true
    namespace: kube-system
  image:
    repository: quay.io/prometheus-operator/prometheus-operator
    tag: v0.43.2-arm64
    sha: ""
    pullPolicy: IfNotPresent
prometheus:

  enabled: true
  prometheusSpec:
    image:
      repository: prom/prometheus
      tag: v2.22.1
