---

- name: Create a Redis namespace
  community.kubernetes.k8s:
    name: redis
    api_version: v1
    kind: Namespace
    state: present

- name: Create Volume for Redis
  community.kubernetes.k8s:
    state: present
    definition: "{{ lookup('template', 'pvc.yml') | from_yaml }}"

- name: Create Secrets for Redis
  community.kubernetes.k8s:
    state: present
    definition: "{{ lookup('template', 'secrets.yml') | from_yaml }}"

- name: Setup Redis Config
  community.kubernetes.k8s:
    state: present
    definition: "{{ lookup('template', 'configmap.yml') | from_yaml }}"

- name: Depoly Redis
  community.kubernetes.k8s:
    state: present
    definition: "{{ lookup('template', 'deploy.yml') | from_yaml }}"

- name: Create Redis Service
  community.kubernetes.k8s:
    state: present
    definition: "{{ lookup('template', 'service.yml') | from_yaml }}"
