---

- name: Create a Redis namespace
  community.kubernetes.k8s:
    name: redis
    api_version: v1
    kind: Namespace
    state: present

- name: Create Volumn for Redis
  community.kubernetes.k8s:
    state: present
    definition: "{{ lookup('file', 'pvc.yml') | from_yaml }}"

- name: Setup Redis Config
  community.kubernetes.k8s:
    state: present
    definition: "{{ lookup('file', 'config.yml') | from_yaml }}"

- name: Depoly Redis
  community.kubernetes.k8s:
    state: present
    definition: "{{ lookup('file', 'deploy.yml') | from_yaml }}"

- name: Create Redis Service
  community.kubernetes.k8s:
    state: present
    definition: "{{ lookup('file', 'service.yml') | from_yaml }}"
