---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-guacamole
  namespace: monitor
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-client
  resources:
    requests:
      storage: 1Gi
