pilot:
  enabled: true
  token: "9d189401-68f2-4ac6-b3fe-c73715672495"

experimental:
  plugins:
    enabled: true

ingressRoute:
  dashboard:
    enabled: true

providers:
  kubernetesCRD:
    enabled: true
  kubernetesIngress:
    enabled: true

logs:
    general:
    level: INFO

globalArguments:
  - "--global.checknewversion"
  - "--global.sendanonymoususage"


additionalArguments:
  - '--api.insecure=true'
  - '--tracing.elastic=true'
  - '--metrics.prometheus=true'

ports:
  traefik:
    port: 9000
    expose: true
    exposedPort: 9000
    protocol: TCP
  web:
    port: 8000
    expose: true
    exposedPort: 80
    protocol: TCP
    nodePort: 32080
    redirectTo: websecure
  websecure:
    port: 8443
    expose: true
    exposedPort: 443
    protocol: TCP
    nodePort: 32443

service:
  enabled: true
  type: LoadBalancer
  spec:
    loadBalancerIP: "192.168.40.100"
