---

alertmanager:
  ingress:
    enabled: false
  persistentVolume:
    enabled: true
    accessModes:
      - ReadWriteOnce
    size: 2Gi
    storageClass: "nfs-client"

kubeStateMetrics:
  enabled: false

server:
  enabled: true
  persistentVolume:
    enabled: true
    accessModes:
      - ReadWriteOnce
    mountPath: /data
    size: 8Gi
    storageClass: "nfs-client"
    subPath: ""
  statefulSet:
    enabled: true

pushgateway:
  enabled: false
  persistentVolume:
    enabled: true
    storageClass: "nfs-client"
