---

image:
  repository: organizr/organizr
  pullPolicy: IfNotPresent
  tag: linux-arm64

strategy:
  type: Recreate

service:
  port:
    port: 80

env:
  branch: v2-master
  PUID: 1000
  PGID: 1000

persistence:
  config:
    enabled: true
    emptyDir: false
    storageClass: "nfs-client"
    accessMode: ReadWriteOnce
    size: 1Gi

probes:
  startup:
    enabled: true
    initialDelaySeconds: 600
    failureThreshold: 30
    periodSeconds: 10
