---
k3s_version: v1.17.5+k3s1
ansible_user: debian
systemd_dir: /etc/systemd/system
master_ip: "{{ hostvars[groups['master'][0]]['ansible_host'] | default(groups['master'][0]) }}"
extra_server_args: ""
extra_agent_args: ""

# cert-manager
cert_manager_crds_url: https://raw.githubusercontent.com/jetstack/cert-manager/release-0.12/deploy/manifests/00-crds.yaml
cert_manager_issuer_prod: certissuer-prod
cert_manager_issuer_staging: certissuer-staging

# network related
metallb_mode: layer2
metallb_address_range: 192.168.1.120-192.168.1.200

# storage options
storage:
  storage_type: device
  device: /dev/sda
  location: /mnt/ssd
  wipe: true

# storage:
#   storage_type: local
#   location: /home/k8s/kube_storage
#   wipe: true
