---
k3s_version: v1.17.5+k3s1
helm_version: v3.3.4
kubernetes_helm_arch: arm64
ansible_user: debian
systemd_dir: /etc/systemd/system
master_ip: "{{ hostvars[groups['master'][0]]['ansible_host'] | default(groups['master'][0]) }}"
extra_server_args: "--disable traefik --disable servicelb --write-kubeconfig-mode 644"
extra_agent_args: ""
remote_tmp: /home/ansible/tmp

# Images
traefik_image: traefik:v2.2
nfs_provisioner_image: quay.io/external_storage/nfs-client-provisioner-arm
jetstack_chart_url: https://charts.jetstack.io
helm_chart_url: https://kubernetes-charts.storage.googleapis.com

# cert-manager
cert_manager_crds_url: https://raw.githubusercontent.com/jetstack/cert-manager/release-0.12/deploy/manifests/00-crds.yaml
cert_manager_issuer_prod: certissuer-prod
cert_manager_issuer_staging: certissuer-staging
acme_email: someone@somewhere.com
acme_staging_url: https://acme-staging-v02.api.letsencrypt.org/directory
acme_prod_url: https://acme-v02.api.letsencrypt.org/directory
dns_domains: someone.com
wdns_domains: "*.someone.com"
#Set get_cert to yes/no if need cert created
get_cert: yes
#Set cert_prod to yes/no if need prod cert needed
cert_prod: no

# network related
metallb_mode: layer2
metallb_address_range: 192.168.1.120-192.168.1.200
network_subnet: 192.168.1.0/24

# storage options
#storage:
#  storage_type: device
#  device: /dev/sda
#  location: /mnt/ssd
#  wipe: true

storage:
  storage_type: local
  location: /home/ansible/kube_storage
  wipe: true

# Authelia details
authelia_logLevel: "trace"
authelia_redirectionurl: "auth.example.com"
authelia_totpissuer: "authelia.com"
#duo:
duo_enabled: false
duo_hostname: api-123456789.example.com
duo_integration_key: ABCDEF
session_name: mccannclan_session
# LDAP authentication Settings
ldap_enabled: true
ldap_url: ldap://openldap.auth.svc.cluster.local
ldap_base_dn: dc=example,dc=com
ldap_user: cn=admin,dc=example,dc=com
ldap_auth_type: config
ldap_port: 389
ldap_tsl: false
# SMTP notification setting
smtp_enabled: true
smtp_username: test
smtp_secure: false
smtp_host: 127.0.0.1
smtp_port: 1025
smtp_sender: admin@example.com
#External Databse Details
externaldb_enabled: true
externaldb_type: mysql
externaldb_url: mysql://mariadb.db.svc.cluster.local
externaldb_database_name: authelia
externaldb_user: authelia
redis_enabled: true
redis_host: redis.db.svc.cluster.local
redis_dbindex: 1
  # Log options debug, verbose, notice, warning
redis_log: verbose
# Unifi controller
unifi_user: test
unifi_url: 127.0.0.1
unifi_port: 8443

#Ingress Service routes
create_ingress: no
ingress_authelia: no
ingress_traefik_dashboard: no
prefex_traefik_dashboard:
ingress_adguard: no
prefex_adguard:
ingress_k8s_dashboard: no
prefex_k8s_dashboard:
ingress_guacamole: no
prefex_guacamole:
ingress_hass_config: no
prefex_hass_config:
ingress_home_assistant: no
prefex_home_assistant:
ingress_grafana: no
prefex_grafana:
ingress_node_red: no
prefex_node_red:
ingress_organizr: no
prefex_organizr:
ingress_phpldapadmin: no
prefex_phpldapadmin:
ingress_prometheus: no
prefex_prometheus:
ingress_tasmoadmin: no
prefex_tasmoadmin:
