---
k3s_version: v1.17.5+k3s1
helm_version: v3.3.4
kubernetes_helm_arch: arm64
ansible_user: debian
systemd_dir: /etc/systemd/system
master_ip: "{{ hostvars[groups['master'][0]]['ansible_host'] | default(groups['master'][0]) }}"
extra_server_args: "--disable traefik --disable servicelb --write-kubeconfig-mode 644"
extra_agent_args: ""
remote_tmp: /home/ansible/tmp

# Images
traefik_image: traefik:v2.2
nfs_provisioner_image: quay.io/external_storage/nfs-client-provisioner-arm
jetstack_chart_url: https://charts.jetstack.io

# cert-manager
cert_manager_crds_url: https://raw.githubusercontent.com/jetstack/cert-manager/release-0.12/deploy/manifests/00-crds.yaml
cert_manager_issuer_prod: certissuer-prod
cert_manager_issuer_staging: certissuer-staging
acme_email: someone@somewhere.com
acme_staging_url: https://acme-staging-v02.api.letsencrypt.org/directory
acme_prod_url: https://acme-v02.api.letsencrypt.org/directory
dns_domains: someone.com
wdns_domains: "*.someone.com"
#Set get_cert to yes/no if need cert created
get_cert: yes
#Set cert_prod to yes/no if need prod cert needed
cert_prod: no

# network related
metallb_mode: layer2
metallb_address_range: 192.168.1.120-192.168.1.200
network_subnet: 192.168.1.0/24

# storage options
#storage:
#  storage_type: device
#  device: /dev/sda
#  location: /mnt/ssd
#  wipe: true

storage:
  storage_type: local
  location: /home/ansible/kube_storage
  wipe: true

# Authelia details
authelia:
  logLevel: "trace"
  redirectionurl: "https://auth.mccannclan.family/"
  totpissuer: "mccannclan.family"

duo:
  enabled: false
  hostname: api-123456789.example.com
  integration_key: ABCDEF

session:
  name: mccannclan_session

ldap:
  enabled: true
  url: ldap://127.0.0.1
  base_dn: dc=mccannclan,dc=family
  user: cn=admin,dc=mccannclan,dc=family

notifier:
    smtp:
      enabled: true
      username: test
      secure: false
      host: 127.0.0.1
      port: 1025
      sender: admin@example.com

#External Databse Details
externaldb:
  enabled: true
  type: mysql
  url: mysql://mariadb.db.cluster.local
  database_name: authelia
  user: authelia
redis:
  enabled: true
  host:
  dbindex: 0
