---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adb
  labels:
    app: adb
spec:
  selector:
    matchLabels:
      app: adb
  replicas: 1
  template:
    metadata:
      labels:
        app: adb
    spec:
      volumes:
        - name: devices
          hostPath:
            path: /dev/bus/usb
            type: Directory
      containers:
        - name: adb
          image: gounthar/docker-adb:aarch64
          ports:
            - containerPort: 5037
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          volumeMounts:
            - name: devices
              mountPath: /dev/bus/usb
          securityContext:
            allowPrivilegeEscalation: true
