---
apiVersion: v1
kind: Service
metadata:
  name: adb
  labels:
    app: adb
spec:
  ports:
    - port: 5037
      targetPort: 5037
  type: LoadBalancer
  loadBalancerIP: 192.168.1.223
  selector:
    app: adb
