---

replicaCount: 1

image:
  repository: osixia/openldap
  tag: stable-arm64v8
  pullPolicy: IfNotPresent

tls:
  enabled: false

service:
  ldapPort: 389
  loadBalancerIP: "192.168.1.221"
  type: LoadBalancer

env:
  LDAP_ORGANISATION: {{ organization_name }}
  LDAP_DOMAIN: {{ dns_domains }}
  LDAP_BACKEND: "mdb"
  LDAP_TLS: "false"
  LDAP_TLS_ENFORCE: "false"
  LDAP_REMOVE_CONFIG_AFTER_SETUP: "true"
  DISABLE_CHOWN: "true"
  LDAP_LOG_LEVEL: "8"

adminPassword: {{ ldap_password }}
configPassword: {{ ldap_password }}

persistence:
  storageClass: "nfs-client"
  accessMode: ReadWriteOnce
  size: 2Gi
