---

- name: Deploy LDAP
  community.kubernetes.helm:
    name: openldap
    chart_ref: madd0c/openldap
    release_namespace: auth
    create_namespace: true
    update_repo_cache: yes
    values: "{{ lookup('template', 'values.yml' ) | from_yaml }}"
