---

#- name: Add madd0c repository
#  community.kubernetes.helm_repository:
#    name: madd0c
#    repo_url: https://madd0c.github.io

- name: Deploy mariadb
  community.kubernetes.helm:
    name: mariadb
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    chart_ref: madd0c/mariadb
    release_namespace: db
    create_namespace: true
    update_repo_cache: yes
    values: "{{ lookup('template', 'values.yml' ) | from_yaml }}" 
