---
#- name: Get helm install script
#  get_url:
#    url: https://get.helm.sh/helm-v3.3.4-linux-arm64.tar.gz
#    dest: "{{ remote_tmp }}/helm.tar.gz"

#- name: Install Helm
#  command: "curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash"
#  
- name: Install Helm (x86)
  unarchive:
    src: "https://get.helm.sh/helm-{{ helm_version }}-linux-amd64.tar.gz"
    dest: /usr/local/bin/helm
    remote_src: yes
  when: ansible_facts.architecture == "x86_64"


- name: Install Helm (arm64)
  unarchive:
    src: "https://get.helm.sh/helm-{{ helm_version }}-linux-arm64.tar.gz"
    dest: /usr/local/bin/helm
    remote_src: yes
  when:
    - ( ansible_facts.architecture is search("arm") and
        ansible_facts.userspace_bits == "64" ) or
      ansible_facts.architecture is search("aarch64")

- name: Install Helm (armhf)
  unarchive:
    src: "https://get.helm.sh/helm-{{ helm_version }}-linux-arm.tar.gz"
    dest: /usr/local/bin/helm
    remote_src: yes
  when:
    - ansible_facts.architecture is search("arm")
    - ansible_facts.userspace_bits == "32"
