---

replicaCount: 1

image:
  repository: billimek/prometheus-speedtest-exporter
  tag: 1.1.0
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 9469

serviceMonitor:
  enabled: true
  interval: "60m"
  scrapeTimeout: 90s
  namespace: default
