---
- name: Add k8s-at-home repository
  community.kubernetes.helm_repository:
    name: k8s-at-home
    repo_url: https://k8s-at-home.com/charts/
    repo_state: present

- name: Deploy MQTT Server
  community.kubernetes.helm:
    name: mqtt
    chart_ref: k8s-at-home/mosquitto
    release_namespace: support
    create_namespace: true
    update_repo_cache: yes
    values: "{{ lookup('template', 'values.yaml' ) | from_yaml }}"
