---

image:
  repository: linuxserver/heimdall
  tag: 2.2.2-ls98
  pullPolicy: IfNotPresent

# upgrade strategy type (e.g. Recreate or RollingUpdate)
strategyType: Recreate

# Probes configuration
probes:
  liveness:
    initialDelaySeconds: 60
    failureThreshold: 5
    timeoutSeconds: 10
  readiness:
    initialDelaySeconds: 60
    failureThreshold: 5
    timeoutSeconds: 10

nameOverride: ""
fullnameOverride: ""

timezone: UTC
puid: 1001
pgid: 1001

service:
  type: ClusterIP
  port: 80
  ## Specify the nodePort value for the LoadBalancer and NodePort service types.
  ## ref: https://kubernetes.io/docs/concepts/services-networking/service/#type-nodeport
  ##
  # nodePort:
  ## Provide any additional annotations which may be required. This can be used to
  ## set the LoadBalancer service type to internal only.
  ## ref: https://kubernetes.io/docs/concepts/services-networking/service/#internal-load-balancer
  ##
  annotations: {}
  labels: {}
  ## Use loadBalancerIP to request a specific static IP,
  ## otherwise leave blank
  ##
  loadBalancerIP:
  # loadBalancerSourceRanges: []
  ## Set the externalTrafficPolicy in the Service to either Cluster or Local
  # externalTrafficPolicy: Cluster

persistence:
  config:
    enabled: true
    storageClass: "-"
    accessMode: ReadWriteOnce
    size: 1Gi
    skipuninstall: false
