---

- name: Deploy phpMyAdmin
  community.kubernetes.helm:
    name: phpmyadmin
  #  kubeconfig: /etc/rancher/k3s/k3s.yaml
    chart_ref: bitnami/phpmyadmin
    release_namespace: db
   # create_namespace: true
    update_repo_cache: yes
    values: "{{ lookup('template', 'values.yml' ) | from_yaml }}"
