---

- name: Check if namespace is present
  community.kubernetes.k8s:
    name: monitor
    api_version: v1
    kind: Namespace
    state: present

- name: Create Volume for Guacamole
  community.kubernetes.k8s:
    state: present
    namespace: monitor
    definition: "{{ lookup('template', 'pvc.yml') | from_yaml }}"

- name: Setup Guacamole Config
  community.kubernetes.k8s:
    state: present
    namespace: monitor
    definition: "{{ lookup('template', 'configmap.yml') | from_yaml }}"

- name: Depoly Guacamole
  community.kubernetes.k8s:
    state: present
    namespace: monitor
    definition: "{{ lookup('template', 'deploy.yml') | from_yaml }}"

- name: Create Guacamole Service
  community.kubernetes.k8s:
    state: present
    namespace: monitor
    definition: "{{ lookup('template', 'service.yml') | from_yaml }}"
