---

image:
  repository: authelia/authelia
  tag: 4
  pullPolicy: IfNotPresent

authelia:
  logLevel: {{ authelia_logLevel }}
  redirectionURL: https://{{ authelia_redirectionurl }}/
  totpIssuer: {{ authelia_totpissuer }}

  duo:
    enabled: {{ duo_enabled }}
    config:
      hostname: {{ duo_hostname }}
      integration_key: {{ duo_integration_key }}

  ldap:
    enabled: {{ ldap_enabled }}
    config:
      url: {{ ldap_url }}
      base_dn: {{ ldap_base_dn }}
      username_attribute: uid
      additional_users_dn: ou=users
      users_filter: (&({username_attribute}={input})(objectClass=person))
      additional_groups_dn: ou=groups
      groups_filter: (&(member={dn})(objectclass=groupOfNames))
      group_name_attribute: cn
      mail_attribute: mail
      user: {{ ldap_user }}

  fileAuth:
    users: {}

  accessControl:
    defaultPolicy: deny
    rules:
      - domain: auth.mccannclan.family.com
        policy: bypass

  session:
    name: {{ session_name }}
    expiration: 5m
    inactivity: 1h
    remember_me_duration: 1M
    domain: {{ dns_domains }}

  regulation:
    max_retries: 3
    find_time: 2m
    ban_time: 10m

  notifier:
    smtpenabled: {{ smtp_enabled }}
    filesystem:
      filename: /config/notification.txt

    smtp:
      username: {{ smtp_username }}
      secure: {{ smtp_secure }}
      host: {{ smtp_host }}
      port: {{ smtp_port }}
      sender: {{ smtp_sender }}

persistence:
  accessMode: ReadWriteOnce
  size: 100Mi

serviceAccount:
  create: true

service:
  type: ClusterIP
  port: 9091

secrets:
  jwt_secret: {{ authelia_jwt }}
  session_secret: {{ authelia_session }}
  duo_secret_key: {{ authelia_duo }}
  redis_password: {{ redis_password }}
  DBPassword: {{ dbuser_password }}
  LDAP_password: {{ ldap_password }}
  smtp_password: {{ email_password }}

redis:
  enabled: {{ redis_enabled }}
  host: {{ redis_host }}
  port: 6379
  database_index: {{ redis_dbindex }}

externaldb:
  enabled: {{ externaldb_enabled }}
  DBType: {{ externaldb_type }}
  DBURL: {{ externaldb_url }}
  Database: {{ externaldb_database_name }}
  DBUser: {{ externaldb_user }}
