---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "{{ dns_domains }}-cert.prod"
  namespace: default
spec:
  secretName: "{{ dns_domains }}-tls-prod"
  issuerRef:
    name: "{{ cert_manager_issuer_prod }}"
    kind: ClusterIssuer
  dnsNames:
    - "{{ dns_domains }}"
    - "{{ wdns_domains }}"
