---

apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: {{cert_manager_issuer_prod}}
spec:
  acme:
    email: {{acme_email}}
    server: {{acme_prod_url}}
    privateKeySecretRef:
      name: {{cert_manager_issuer_prod}}
    solvers:
      - dns01:
        digitalocean:
          tokenSecretRef:
            name: digitalocean-dns
            key: access-token
