---

accessControl:
   rules:
      # Rules applied to everyone
      - domain: auth.mccannclan.family.com
        policy: allow

      #- domain: secure.example.com
      #  policy: one_factor
      ## Network based rule, if not provided any network matches.
      #  networks:
      #  - 192.168.1.0/24

      #- domain:
      #  - secure.example.com
      #  - private.example.com
      #    policy: two_factor

      #- domain: singlefactor.example.com
      #  policy: one_factor

      ## Rules applied to 'admins' group
      #- domain: "mx2.mail.example.com"
      #  subject: "group:admins"
      #  policy: deny

      #- domain: "*.example.com"
      #  subject:
      #    - "group:admins"
      #    - "group:moderators"
      #  policy: two_factor

      ## Rules applied to 'dev' group
      #- domain: dev.example.com
      #  resources:
      #    - "^/groups/dev/.*$"
      #  subject: "group:dev"
      #  policy: two_factor

      ## Rules applied to user 'john'
      #- domain: dev.example.com
      #  resources:
      #    - "^/users/john/.*$"
      #  subject: "user:john"
      #  policy: two_factor

      # Rules applied to user 'harry'
      #- domain: dev.example.com
      #  resources:
      #    - "^/users/harry/.*$"
      #  subject: "user:harry"
      #  policy: two_factor

      # Rules applied to user 'bob'
      #- domain: "*.mail.example.com"
      #  subject: "user:bob"
      #  policy: two_factor
      #- domain: "dev.example.com"
      #  resources:
      #    - "^/users/bob/.*$"
      #  subject: "user:bob"
      #  policy: two_factor
