---
- name: Clone Cluster Monitoring Repo
  git:
    repo: https://github.com/carlosedp/cluster-monitoring.git
    dest: "{{ temp_dir }}/cluster-monitoring"

- name: Remove base settings file
  file:
    path: "{{ temp_dir }}/cluster-monitoring/vars.jsonnet"
    state: absent

- name: Copy Cluster Monitoring settings file
  copy:
     src: vars.jsonnet
     dest: "{{ temp_dir }}/cluster-monitoring/vars.jsonnet"
     owner: ansible

- name: Copy Metallb Instalastion files
  copy:
     src: setup.sh
     dest: "{{ temp_dir }}/cluster-monitoring/setup.sh"
     owner: ansible
     mode: '0700'

- name: Install Cluster Monitoring
  command: "sh {{ temp_dir }}/cluster-monitoring/setup.sh"
  
