---
- name: Add k8s-at-home repository
  community.kubernetes.helm_repository:
    name: k8s-at-home
    repo_url: https://k8s-at-home.com/charts/
    repo_state: present

- name: Deploy digitalocean-dyndns
  community.kubernetes.helm:
    name: digitalocean-dyndns
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    chart_ref: k8s-at-home/digitalocean-dyndns
    release_namespace: kube-system
    update_repo_cache: yes
    values: "{{ lookup('template', 'values.yaml' ) | from_yaml }}"
