---

- name: Install middlewares
  community.kubernetes.k8s:
    state: present
    definition: "{{ lookup('file', 'middleware-https-only.yaml') | from_yaml }}"

- name: Install middlewares
  community.kubernetes.k8s:
    state: present
    definition: "{{ lookup('file', 'middleware-rate-limit.yaml') | from_yaml }}"

- name: Install middlewares
  community.kubernetes.k8s:
    state: present
    definition: "{{ lookup('file', 'middleware-headers.yaml') | from_yaml }}"

- name: Install middlewares
  community.kubernetes.k8s:
    state: present
    definition: "{{ lookup('file', 'middleware-basicauth.yaml') | from_yaml }}"

- name: Install middlewares
  community.kubernetes.k8s:
    state: present
    definition: "{{ lookup('file', 'middleware-authelia.yaml') | from_yaml }}"

- name: Install middleware chains
  community.kubernetes.k8s:
    state: present
    definition: "{{ lookup('file', 'middleware-chains-no-auth.yaml') | from_yaml }}"

- name: Install middleware chains
  community.kubernetes.k8s:
    state: present
    definition: "{{ lookup('file', 'middleware-chain-basic-auth.yaml') | from_yaml }}"

- name: Install middleware chains
  community.kubernetes.k8s:
    state: present
    definition: "{{ lookup('file', 'middleware-chain-authelia.yaml') | from_yaml }}"

- name: Install tls options
  community.kubernetes.k8s:
    state: present
    definition: "{{ lookup('file', 'tsl-options.yaml') | from_yaml }}"

- name: Install tls store
  community.kubernetes.k8s:
    state: present
    definition: "{{ lookup('file', 'tsl-store.yaml') | from_yaml }}"

- name: Install External Ingress
  community.kubernetes.k8s:
    state: present
    definition: "{{ lookup('file', 'ingress-traefik.yaml') | from_yaml }}"
