---

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingressroute-authelia
  namespace: default
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`{{ authelia_redirectionurl }}`)
      kind: Rule
      services:
        - name: authelia
          namespace: auth
          port: 9091
      middlewares:
        - chain-authelia
  tls:
    store:
      name: default
