---

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingressroute-kubernetes-dashboard
  namespace: default
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`{{ prefex_k8s_dashboard }}.{{ dns_domains }}`)
      kind: Rule
      services:
        - name: kubernetes-dashboard
          namespace: kube-system
          port: 8080
      middlewares:
        - chain-authelia
      #  - chain-basic-auth
      #  - chain-no-auth
  tls:
    store:
      name: default
