---

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingressroute-guacamole
  namespace: default
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`{{ prefex_guacamole }}.{{ dns_domains }}`)
      kind: Rule
      services:
        - name: guacamole
          namespace: monitor
          port: 8080
      middlewares:
        - name: chain-authelia
          namespace: default
  tls:
    store:
      name: default
