---

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingressroute-hass-config
  namespace: default
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`hassconfig.mccannclan.family`)
      kind: Rule
      services:
        - name: home-assistant
          namespace: home
          port: 80
  #  middlewares:
  #  - chain-authelia
  #  - chain-basic-auth
  #  - chain-no-auth
  tls:
    store:
      name: default
