---

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingressroute-home-assistant
  namespace: default
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`{{ prefex_home_assistant }}.{{ dns_domains }}`)
      kind: Rule
      services:
        - name: home-assistant
          namespace: home
          port: 8123
  #  middlewares:
  #  - chain-authelia
  #  - chain-basic-auth
  #  - chain-no-auth
  tls:
    store:
      name: default
