---

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingressroute-grafana
  namespace: default
spec:
  entryPoints:
  - web
  - websecure
  middlewares:
  - chain-authelia
#  - chain-basic-auth
#  - chain-no-auth
  routes:
  - match: Host(`{{ prefex_grafana }}.{{ dns_domains }}`)
    kind: Rule
    services:
    - name: grafana
      namespace: monitor
      port: 80
  tls:
    store:
      name: default
