---

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingressroute-node-red
  namespace: default
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`{{ prefex_node_red }}.{{ dns_domains }}`)
      kind: Rule
      services:
        - name: node-red
          namespace: home
          port: 1880
      middlewares:
        - name: chain-authelia
          namespace: default
  tls:
    store:
      name: default
