---

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingressroute-organizr
  namespace: default
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`{{ prefex_organizr }}.{{ dns_domains }}`)
      kind: Rule
      services:
        - name: organizr
          namespace: home
          port: 80
      middlewares:
        - chain-authelia
      #  - chain-basic-auth
      #  - chain-no-auth
  tls:
    store:
      name: default
