---

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingressroute-tasmoadmin
  namespace: default
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`{{ prefex_tasmoadmin }}.{{ dns_domains }}`)
      kind: Rule
      services:
        - name: tasmoadmin
          namespace: home
          port: 80
      middlewares:
        - name: chain-authelia
          namespace: default
  tls:
    store:
      name: default
