---

image:
  repository: mariadb
  tag: latest
  pullPolicy: IfNotPresent

clusterDomain: cluster.local

auth:
  rootPassword: "{{ mariadb_root_pw }}"
  replicationUser: replicator
  replicationPassword: ""
  forcePassword: false
  usePasswordFiles: false

primary:
  command: []
  args: []
  configuration: |-
    [mysqld]
    skip-name-resolve
    port=3306
    max_allowed_packet=16M
    bind-address=0.0.0.0
    character-set-server=UTF8
    collation-server=utf8_general_ci
    [client]
    port=3306
    default-character-set=UTF8
    [manager]
    port=3306
  updateStrategy: RollingUpdate

  persistence:
    enabled: true
    storageClass: "nfs-client"
    annotations: {}
    accessModes:
      - ReadWriteOnce
    size: 2Gi
    selector: {}

  service:
    type: LoadBalancer
    port: 3306
    loadBalancerIP: "192.168.1.220"
