---

- name: Add Celtic repository
  community.kubernetes.helm_repository:
    name: celtic
    repo_url: https://cetic.github.io/helm-charts

- name: Deploy Adminer
  community.kubernetes.helm:
    name: adminer
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    chart_ref: cetic/adminer
   # release_namespace: db
    create_namespace: true
    update_repo_cache: yes
   # values: "{{ lookup('template', 'values.yml' ) | from_yaml }}" 
