---
- name: Add k8s-at-home repository
  community.kubernetes.helm_repository:
    name: k8s-at-home
    repo_url: https://k8s-at-home.com/charts/
    repo_state: present

- name: Deploy Prometheus Blackbox Exporter
  community.kubernetes.helm:
    name: prometheus-blackbox-exporter
    chart_ref: k8s-at-home/prometheus-blackbox-exporter
    release_namespace: monitor
    update_repo_cache: yes
    values: "{{ lookup('template', 'values.yaml' ) | from_yaml }}"
