additionalArguments:
            - '--entryPoints.traefik.address=:9000'
            - '--entryPoints.web.address=:8000'
            - '--entryPoints.websecure.address=:8443'
            - '--api.dashboard=true'
            - '--api.insecure=true'
            - '--accesslog=true'
            - '--log.level=INFO'
            - '--ping=true'
            - '--providers.kubernetescrd'
            - '--providers.kubernetesingress'
            - '--metrics.prometheus=true'
            - '--tracing.elastic=true'
            - '--entrypoints.web.http.redirections.entryPoint.to=websecure'
            - '--entrypoints.web.http.redirections.entryPoint.scheme=https'
