---
serviceAccount:
  create: true
service:
  type: LoadBalancer
  loadBalancerIP: "192.168.40.201"
persistence:
  enabled: true
  storageClass: nfs-client
  size: 1Gi

# Any extra volumes to define for the pod
#extraVolumes:
    - name: mqttauth
      secret:
        secretName: mosquitto-auth-secrets

# Any extra volume mounts to define for the containers
#extraVolumeMounts:
    - name: mqttauth
      mountPath: /mosquitto/config/passwords.txt

customConfig:
    port 1883
    autosave_interval 1800
    persistence true
    persistence_location /mosquitto/data/
    password_file /mosquitto/config/passwords.txt

monitoring:
  podMonitor:
    enabled: true
  sidecar:
    enabled: true
