---

- name: Add jetstack repo
  community.kubernetes.helm_repository:
    name: jetstack
    repo_url: "{{ jetstack_chart_url }}"
    
- name: Install cert-manager from helm
  community.kubernetes.helm:
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    name: cert-manager
    chart_ref: jetstack/cert-manager 
    release_namespace: cert-manager
    create_namespace: true
    values: "--set installCRDs=true"
    
- name: Copy over clusterIssuer files
  template:
    src: "{{ item }}"
    dest: "{{ remote_tmp }}/{{ item }}"
  with_items:
    - prod-clusterissuer.yaml
    - staging-clusterissuer.yaml
    - do-secrets.yaml

- name: Import secret
  k8s:
    state: present
    namespace: cert-manager
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    src: "{{ remote_tmp }}/do-secrets.yaml"

- name: Remove secret file
  file:
    path: "{{ remote_tmp }}/do-secrets.yaml"
    state: absent
    
- name: Creating Certificate Issuers
  k8s:
    state: present
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    src: "{{ remote_tmp }}/{{ item }}"
  with_items:
    - prod-clusterissuer.yaml
    - staging-clusterissuer.yaml
