---

- name: Wait for all cert-manager pods become created
  shell: "kubectl get po --namespace=cert-manager --output=jsonpath='{.items[*].metadata.name}'"
  register: cert_manager_pods_created
  until: item in cert_manager_pods_created.stdout
  retries: 10
  delay: 30
  with_items:
    - cert-manager
    - cert-manager-cainjector
    - cert-manager-webhook

- name: Wait for cert-manager pods become ready
  shell: "kubectl wait --namespace=cert-manager --for=condition=Ready pods --all --timeout=600s"
  register: cert_manager_pods_ready

- name: Copy over clusterIssuer files
  template:
    src: "{{ item }}"
    dest: "{{ remote_tmp }}/{{ item }}"
  with_items:
    - prod-clusterissuer.yaml
    - staging-clusterissuer.yaml
    - do-secrets.yaml

- name: Import secret
  k8s:
    state: present
    namespace: cert-manager
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    src: "{{ remote_tmp }}/do-secrets.yaml"

- name: Remove secret file
  file:
    path: "{{ remote_tmp }}/do-secrets.yaml"
    state: absent
    
- name: Creating Certificate Issuers
  k8s:
    state: present
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    src: "{{ remote_tmp }}/{{ item }}"
  with_items:
    - prod-clusterissuer.yaml
    - staging-clusterissuer.yaml
