---

- name: Deploy LDAP
  community.kubernetes.helm:
    name: openldap
    #kubeconfig: /etc/rancher/k3s/k3s.yaml
    chart_ref: stable/openldap
    release_namespace: auth
    create_namespace: true
    update_repo_cache: yes
    values: "{{ lookup('template', 'values.yml' ) | from_yaml }}" 
